import { expect, test } from '@playwright/test'
test('lead can recover the Version 7 owner-save regression', async ({ page }) => {
  await page.goto('/'); await page.locator('.desktop-queue').getByRole('button', { name: /open incident inc-0003/i }).click()
  const drawer = page.locator('.app-layout .detail-sidebar')
  await drawer.getByLabel('Owner').selectOption('Chen Wei'); await page.getByLabel('Save outcome').selectOption('failure')
  await drawer.getByRole('button', { name: 'Save owner change' }).click(); await expect(drawer.getByRole('alert')).toContainText('not saved')
  await page.getByLabel('Save outcome').selectOption('success'); await drawer.getByRole('button', { name: 'Retry owner change' }).click()
  await expect(drawer.getByText(/saved for this browser session/i)).toBeVisible()
})
test('load error retries through loading and returns the deterministic queue', async ({ page }) => {
  await page.goto('/'); await page.getByLabel('Queue source').selectOption('error'); await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('button', { name: /retry loading queue/i }).click(); await expect(page.getByRole('heading', { name: 'Loading incidents' })).toBeVisible(); await expect(page.getByText('20 of 20 incidents')).toBeVisible()
})
test('drawer keeps keyboard focus contained and supports reverse wrapping', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/'); await page.locator('.mobile-cards').getByRole('button', { name: /open incident inc-0003/i }).click()
  const drawer = page.locator('.mobile-sheet'); const back = drawer.getByRole('button', { name: 'Back' }); const save = drawer.getByRole('button', { name: 'Save owner change' })
  await save.focus(); await page.keyboard.press('Tab'); await expect(back).toBeFocused()
  await back.focus(); await page.keyboard.press('Shift+Tab'); await expect(save).toBeFocused()
})

test('uses the approved desktop, tablet, and mobile queue-to-detail treatments', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 }); await page.goto('/')
  await expect(page.locator('.desktop-queue table')).toBeVisible()
  await page.locator('.desktop-queue').getByRole('button', { name: /open incident inc-0003/i }).click()
  const selectedRow = page.locator('.desktop-queue').getByRole('button', { name: /open incident inc-0003/i })
  await expect(selectedRow).toHaveAttribute('aria-current', 'true')
  await expect(selectedRow).toHaveClass(/queue-row-selected/)
  await expect(selectedRow).toHaveCSS('box-shadow', /rgb\(137, 180, 232\)/)
  await expect(page.locator('.detail-sidebar').first()).toHaveCSS('width', '420px')
  await page.locator('.app-layout .detail-sidebar').getByRole('button', { name: 'Close incident details' }).click()

  await page.setViewportSize({ width: 900, height: 900 })
  await expect(page.locator('.desktop-queue table')).toBeVisible()
  await expect(page.locator('.desktop-queue thead th:visible')).toHaveCount(4)
  await expect(page.locator('.desktop-queue thead th', { hasText: 'Service' })).toBeHidden()
  await expect(page.locator('.desktop-queue thead th', { hasText: 'Owner' })).toBeHidden()
  await expect(page.locator('.desktop-queue thead th', { hasText: 'Incident' })).toBeVisible()
  await expect(page.locator('.desktop-queue thead th', { hasText: 'Severity' })).toBeVisible()
  await expect(page.locator('.desktop-queue thead th', { hasText: 'Status' })).toBeVisible()
  await expect(page.locator('.desktop-queue thead th', { hasText: 'Updated' })).toBeVisible()
  await page.locator('.desktop-queue').getByRole('button', { name: /open incident inc-0003/i }).click()
  await expect(page.locator('.detail-sidebar').first()).toBeHidden()
  await expect(page.locator('.mobile-sheet')).toBeVisible()
  await page.locator('.mobile-sheet').getByRole('button', { name: 'Close incident details' }).click()

  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.desktop-queue')).toBeHidden()
  await expect(page.locator('.incident-card').first()).toHaveCSS('border-radius', '8px')
  await page.locator('.mobile-cards').getByRole('button', { name: /open incident inc-0003/i }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('.mobile-sheet')).toHaveCSS('width', '390px')
  await expect(page.locator('.mobile-sheet .drawer-top')).toHaveCSS('position', 'sticky')
})

test('Make V7 filter controls close on outside click and Escape with focus restoration', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 }); await page.goto('/')
  const severity = page.getByRole('button', { name: /severity/i })
  await severity.click(); await expect(severity).toHaveAttribute('aria-expanded', 'true')
  await page.locator('h1').click(); await expect(severity).toHaveAttribute('aria-expanded', 'false')
  await expect(severity).toBeFocused()
  await severity.click(); await page.keyboard.press('Escape')
  await expect(severity).toHaveAttribute('aria-expanded', 'false')
  await expect(severity).toBeFocused()

  await page.setViewportSize({ width: 390, height: 844 })
  const filters = page.getByRole('button', { name: 'Filters' })
  await filters.click(); await expect(page.getByRole('dialog', { name: 'Filter incidents' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Filter incidents' })).toBeHidden()
  await expect(filters).toBeFocused()
})
